# Parts-of-Speech (POS) Tagging

## Introduction

 Suppose we have 2 *sentences* :

1. *Plant* need light and water.
2. Everyone should *plant* more trees.

Here the word **plant** has 2 different meanings in the above 2 sentences. In the first sentence, plant refers to a living organism and is used as a *Noun* whereas in the second sentence, plant has been used as a *Verb* which refer to put something in ground to grow.

When we say these sentences to a person, the person would be able to differentiate between the meanings of the 2 sentences but suppose we want a machine to understand the meaning of the sentence, then we would  need to disambiguate the meaning of the word _plant_.

Hence, if we are able to figure out the correct meaning of plant which is used in the sentence, we can infer the meaning of the sentence.

## Motivation

To try to automate the process of finding the usage of the word based its context.

## What is POS Tagging ?

POS Tags are the **tags corresponding to the classification of the word as a Noun, Verb, Adjectives, etc**.

In simple terms, POS(Parts-of-Speech) Tagging is nothing but to classify whether a word is a :-

* Noun
* Verb
* Adjectives
* Adverbs
* Pronouns
* Interjections
* Conjunctions
* Prepositions

For example : The POS Tags for the words of the sentence : *I like playing chess* the POS Tags are as follows:

* I       -> Pronoun
* like    -> Verb
* playing -> Verb
* Chess   -> Noun

It is possible that a single word has more than one POS Tag as it might appear in different context in different sentences, as seen for the above case(_plant_).

## Is it useful?

POS is useful because it :
1. Gives a lot of information about a word and its neighbouring words
2. Can be used for:
    * Syntactic parsing of a sentence
    * Named Entity Recognition 
    * Information Extraction
    * Text to Speech conversion

## How to do POS Tagging

One way to do POS Tagging is tagging the words in the sentence manually.
* Problems : 
   * Time consuming
   * Not scalable
* Solution :
   * Try to ** automate the process** 

## Probabilistic POS Tagging

To automate the process of POS Tagging, we would use probabiltic approach to model our problem.

We will consider *fine grained* tag sets. 
Fine grain tags sets are those sets in which tags are subdivided.For example: Tag Noun is broken into the following sub-parts:

* Common
* Proper
* Abstract
* Possessive
* Collective

Here each of the sub-tag will have a unique tag associated to it.

Likewise, the other Tags (Verb, Adjective, ect) are also subdivided.

## Hidden Markov Model (HMM) POS Tagging

### Introduction

* The model is trained on a fully annotated dataset in which each word in a sentence is annotated with a POS Tag.
* We observe the words
* The tags are hidden as they are not observed


### Task

Given a set of sequence of words (W), find the corresponding sequence of tags for the given words.

### Mathematical Calculations

T<sup>opt</sup> = argmax<sub>T</sub> P(T|W)

T<sup>opt</sup> = argmax<sub>T</sub>$\frac{P(W|T)P(T)}{P(W)}$    (Using Bayes Theorem)

T<sup>opt</sup> = argmax<sub>T</sub> P(W|T)P(T)    (since P(W) will remain same for all the tag sequence)

Let W = w<sub>1</sub>w<sub>2</sub>...w<sub>n</sub>

and T = t<sub>1</sub>t<sub>2</sub>...t<sub>n</sub>

T<sup>opt</sup> = argmax<sub>T</sub> P(w<sub>1</sub>w<sub>2</sub>...w<sub>n</sub>|t<sub>1</sub>t<sub>2</sub>...t<sub>n</sub>)P(t<sub>1</sub>t<sub>2</sub>...t<sub>n</sub>)   

T<sup>opt</sup> = argmax<sub>T</sub> $\prod_{i=1}^{n}$ P(w<sub>i</sub>|t<sub>1</sub>t<sub>2</sub>...t<sub>n</sub>w<sub>1</sub>w<sub>2</sub>...w<sub>i-1</sub>)P(t<sub>i</sub>|t<sub>1</sub>t<sub>2</sub>...t<sub>i-1</sub>)   


### Assumptions

1. P(w<sub>i</sub>|t<sub>1</sub>t<sub>2</sub>...t<sub>n</sub>w<sub>1</sub>w<sub>2</sub>...w<sub>i-1</sub>) = P(w<sub>i</sub>|t<sub>i</sub>) i.e. w<sub>i</sub> depends only on t<sub>i</sub> and not on other tags. We will call this **Emission Probability**


2. P(t<sub>i</sub>|t<sub>1</sub>t<sub>2</sub>...t<sub>i-1</sub>) = P(t<sub>i</sub>|t<sub>i-1</sub>) i.e. t<sub>i</sub> depends only on t<sub>i-1</sub> and not on other tags. We will call this **Transmission Probability**


3. P(t<sub>i</sub>|t<sub>i-1</sub>) = $\frac{C(t_{i-1},t_{i})}{C(t_{i-1})}$  where 
    * C(t<sub>i-1</sub>,t<sub>i</sub>) denotes the number of times tag t<sub>i-1</sub> and t<sub>i</sub> appear together.
    * C(t<sub>i-1</sub>) denotes the number of times tag t<sub>i-i</sub> appear in the corpus.
    
    
    
4. P(w<sub>i</sub>|t<sub>i</sub>) = $\frac{C(w_{i},t_{i})}{C(t_{i})}$  where 
    * C(w<sub>i</sub>,t<sub>i</sub>) denotes the number of times word w<sub>i</sub> is assigned t<sub>i</sub> tag.
    * C(t<sub>i</sub>) denotes the number of times tag t<sub>i</sub> appear in the corpus.

Based on the above assumptions we get : 
T<sup>opt</sup> = argmax<sub>T</sub> $\prod_{i=1}^{n}$ P(w<sub>i</sub>|t<sub>i</sub>)P(t<sub>i</sub>|t<sub>i-1</sub>) 

## Viterbi Decoding

Consider the following image
![viterbi](viterbi.jpg)


At each step, for each tag of a word we will store which previous tag gives the highest probability.

Consider two 2-D Matrices

    1. Viterbi
    2. Index
    
Viterbi[i][j] = maximum probability of the sequence of words w<sub>1</sub>w<sub>2</sub>...w<sub>j</sub> if the tag of w<sub>j</sub> is the i<sup>th</sup> tag corresponding to w<sub>j</sub>

Index[i][j] will store the index of the tag of the previous word which corresponds to the maximum probabilty for the j<sup>th</sup> word to have i<sup>th</sup> tag

The size of both the matrix will be T $\times$N where
   * T = Maximum tags of any word in the sentence.
   * N = Number of words in the sentence.

   
In the above example the size of the matrix is 4 $\times$5


### Computing Cells of the matrix

For computing cells (i,j) for the matrix, use the following relation:

Viterbi[i][j]=$ max_{k=1..T}${ Viterbi[k][j-1] $\times$ P(i<sup>th</sup> tag corresponding to the j<sup>th</sup> word | k<sup>th</sup> tag corresponding to the (j-1)<sup>th</sup> word) $\times$ P(j<sup>th</sup> word | i<sup>th</sup> tag corresponding to the j<sup>th</sup> word)} 

Index[i][j]=$ argmax_{k=1..T}${ Viterbi[k][j-1] $\times$ P(i<sup>th</sup> tag corresponding to the j<sup>th</sup> word | k<sup>th</sup> tag corresponding to the (j-1)<sup>th</sup> word) $\times$ P(j<sup>th</sup> word | i<sup>th</sup> tag corresponding to the j<sup>th</sup> word)} 


For the above example suppose we want to compute Viterbi[2][4], then 

Viterbi[2][4]=$ max_{k=1..4}${ Viterbi[k][3] $\times$ P(DT|k<sup>th</sup> tag corresponding to the word *back*(if k=1,then it is RB)) $\times$ P(the|DT)} 


The initialisations of the matrix can be done as follows:

Let S be the POS tag for start symbol, then 

dp[i][1] = =$ max_{k=1..T}${P((i<sup>th</sup> tag corresponding to the 1<sup>st</sup> word | S) $\times$ P(1<sup>st</sup> word | i<sup>th</sup> tag corresponding to the 1<sup>st</sup> word)} 



### Backtracking the optimal sequence of tags

To Backtrack the optimal sequence of tags for the given word sequence we will use the Index matrix.

1. Find $ argmax_{k=1..T}$Viterbi[k][N]

2. Iteratively, trace back to the appropriate index using the Index matrix until we have reached the 1<sup>st</sup> word. 

3. Also, at each iteration store the corresponding tag of the word.

The sequence of tags obtained willbe the optimal sequence.

### Complexity Analysis

1. Time = O(NT<sup>2</sup>)
2. Space = O(NT)

Below is the implmenting of the above mentioned algorithm.

## Importing libraries

* I am importing all the libraries that will be required.

In [51]:
import nltk
from nltk.tokenize import word_tokenize
import numpy as np

## Extracting the words and tags from the dataset

* Used BERP dataset for training our model . i.e. computing emmission and transmission probabilities.
* Extracting the words along with their tags. 
* Next, I have separated the words and tags.
* Stored the different tags which have appeared for a word
* Maintaing the unigram count of the word and the tag appearing in the corpus.

In [52]:
f=open('Train_Viterbi.txt','r')

words={}
tags_unigram={}
sentences=f.readlines()
possible_tags={}
tags_count=0
words_count=0
for i in range(len(sentences)):
    word_tag=sentences[i].split('\t')
    if(len(word_tag)==2):
        word=word_tag[0]
        tag=word_tag[1]
        tag=tag[:len(tag)-1]
        if(word=='.' or word=='?' or word=='!'):
            word='<s>'
            tag='<s>'
            sentences[i]='<s>'+'\t'+'<s>'
        if(word not in possible_tags):
            possible_tags[word]=[tag]
        else:
            if(tag not in possible_tags[word]):
                possible_tags[word].extend([tag])
        words[word]=words.get(word,0)+1
        tags_unigram[tag]=tags_unigram.get(tag,0)+1
        tags_count+=1
        words_count+=1
    if(sentences[i]=='\n'):
        sentences[i]='<s>'+'\t'+'<s>'

## Training our model

* We would be calculating the Emmission and Transmission Probabilities from our training dataset

## Calculating Transmission Probabilites

* Calculating the count of all possible tag bigrams which apperar in the corpus

In [53]:
tags_bigram={}
for i in range(len(sentences)-1):
    tag_1=sentences[i].split('\t')[1]
    tag_2=sentences[i+1].split('\t')[1]
    if(tag_1!='<s>'):
        tag_1=tag_1[:len(tag_1)-1]
    if(tag_2!='<s>'):
        tag_2=tag_2[:len(tag_2)-1]
    tag=tag_1+" "+tag_2
    tags_bigram[tag]=tags_bigram.get(tag,0)+1

* Finding the transmission probabilites using the bigram count and the unigram count of the tags.

In [54]:
transmission_prob={}

for i in tags_bigram:
    split=i.split()
    key=split[0]
    transmission_prob[i]=tags_bigram[i]/(1.0*tags_unigram[key])

## Calculating Emmision Probabilites

* Calculating the tag-word frequency(count) - i.e. the number of times a word and a tag appeared together in the corpus

In [55]:
tag_word={}
for i in range(len(sentences)):
    line =sentences[i].split('\t')
    word=line[0]
    tag=line[1]
    if(tag!='<s>'):
        tag=tag[:len(tag)-1]
    key=tag+" "+word
    tag_word[key]=tag_word.get(key,0)+1

* Calculating the Emmision probabilities using the tag-word frequncy and the unigram count of the tags.

In [56]:
emission_prob={}
for i in tag_word:
    split=i.split()
    tag=split[0]
    emission_prob[i]=tag_word[i]/(1.0*tags_unigram[tag])

## Testing

* We take an input sentence to test our trained model

In [57]:
sentence="i like food"

tokens=[]
tokens.append('<s>')
tokens.extend(word_tokenize(sentence))

* We will run the Viterbi algorithm
* To do this,we would need the following things
    * 2 matrix for
        1. Storing the calculated probabilities in each step of the iteration of the algorithm (The required matrix is viterbi_prob).
        2. Storing the tag of the previous word ((i-1)<sup>th</sup>) which is most probable to for the j<sup>th</sup> tag of the i<sup>th</sup> word.(The required matrix is viterbi_prob_index)
    * Transmission probabilties
    * Emission probabilties
* I am printing the viter_prob matrix at each iteration so as to better understand the working of the algorithm

In [58]:
viterbi_prob=np.zeros((len(tokens),len(tokens)))
viterbi_prob_index=np.zeros((len(tokens),len(tokens)))
w=1

for i in range(1,len(tokens)):
    print
    possibleCurrentTags=possible_tags[tokens[i]]
    previousTags=possible_tags[tokens[i-1]]
    current_word=tokens[i]
    t=1
    for j in range(len(possibleCurrentTags)):
        print
        print "Word "+str(w)+" Tag "+str(t)
        print
        t+=1
        if(i==1):
            current_tag=possibleCurrentTags[j]
            maximum=-1
            index=-1
            for k in range(len(previousTags)):
                previous_tag=previousTags[k]
                possible_ans=transmission_prob[previous_tag+" "+current_tag]*emission_prob[current_tag+" "+current_word]
                if(maximum<possible_ans):
                    maximum=possible_ans
                    index=k
            viterbi_prob[j][i]=maximum
            viterbi_prob_index[j][i]=index
        else:
            current_tag=possibleCurrentTags[j]
            maximum=-1
            index=-1
            for k in range(len(previousTags)):
                previous_tag=previousTags[k]
                possible_ans=viterbi_prob[k][i-1]*transmission_prob[previous_tag+" "+current_tag]*emission_prob[current_tag+" "+current_word]
                if(maximum<possible_ans):
                    maximum=possible_ans
                    index=k
            viterbi_prob[j][i]=maximum
            viterbi_prob_index[j][i]=index
        print "Matrix : \n" ,viterbi_prob
    w+=1



Word 1 Tag 1

Matrix : 
[[0.         0.21458124 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]


Word 2 Tag 1

Matrix : 
[[0.         0.21458124 0.00591492 0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

Word 2 Tag 2

Matrix : 
[[0.         0.21458124 0.00591492 0.        ]
 [0.         0.         0.00235987 0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

Word 2 Tag 3

Matrix : 
[[0.00000000e+00 2.14581243e-01 5.91492077e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.35986886e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.03415876e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]]

Word 2 Tag 4

Matrix : 
[[0.00000000e+00 2.14581243e-01 5.91492077e-03 0.0000

* Find the correct combination of the tags of the word which gives the maximum probability of the given sentence.
* We will use viterbi_prob_index matrix for finding the correct tag of each word

In [59]:
ans={}
i=len(tokens)-1
maximum=-1
index=-1
for j in range(len(tokens)):
    if(viterbi_prob[j][i]>maximum):
        maximum=viterbi_prob[j][i]
        index=j
while(i>0):
    ans[tokens[i]]=possible_tags[tokens[i]][int(index)]
    index=viterbi_prob_index[int(index)][i]
    i-=1      

## Output

* This is the final output of the input sentence.

In [60]:
for i in range(1,len(tokens)):
    print tokens[i] + " --> "+ ans[tokens[i]]

i --> PRP
like --> VB
food --> NN


## References

1. Jurafsky, Dan. Speech & language processing. Pearson Education India, 2000.
2. https://medium.freecodecamp.org/an-introduction-to-part-of-speech-tagging-and-the-hidden-markov-model-953d45338f24
3. Class Notes

**Image Reference**

1. Jurafsky, Dan. Speech & language processing. Pearson Education India, 2000.